name = "analityka-krop-api"
main = "worker/src/index.ts"
compatibility_date = "2026-06-06"
compatibility_flags = ["nodejs_compat"]
account_id = "7ca9a7fab54e9acdd7d234f1547058bc"

[[d1_databases]]
binding = "DB"
database_name = "anal"
database_id = "1cdd05a3-11b0-447d-ae91-ac0bcfff20d0"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGIN = "https://analityka-krop.pages.dev"
